name = "inkmint-api"
main = "src/index.js"
compatibility_date = "2024-12-01"
routes = [
  { pattern = "api.inksuite.xyz", custom_domain = true }
]

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "inksuite-storage"

# [C-02] KV namespace for tracking used transaction hashes
[[kv_namespaces]]
binding = "USED_TXS"
id = "19a9ecc0c73f428bac02daef27276067"

[vars]
ALLOWED_ORIGIN = "https://mint.inksuite.xyz"
